language: java
jdk:
  - openjdk8
  -
branches:   # Travis CI를 어느 브랜치가 푸시될 때 수행할지를 지정한다.
  only:
    - master

#Travis CI 서버의 Home

cache:      # 그레들을 통해 의존성을 받게 되면 이를 해당 디렉토리에 캐시해서, 같은 의존성은 다음 배포 때부터 다시 받지 않도록 설정한다.
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"
# master 브랜치에 푸시되었을 때 수행하는 명령어. 여기서는 프로젝트 내부에 둔 gradlew 를 통해 clean & build를 수행한다.

before_install:
  - chmod +x gradlew

before_deploy:                                                        # deploy 명령어가 실행되기 전에 수행
  - mkdir -p before-deploy                                            # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *                        # before-deploy 로 이동 후 전체 압축
  - cd ../ && mkdir -p deploy                                         # 상위 디렉토리 이동 후 deploy 폴더 생성
  - mv before-deploy/before-deploy.zip deploy/SpringBoot_IntelliJ.zip # deploy로 zip파일 이동

  #- zip -r SpringBoot_IntelliJ *  #SpringBoot_IntetlliJ 이름으로 파일을 압축시킴.
  #- mkdir -p deploy
  #- mv SpringBoot_IntelliJ.zip deploy/SpringBoot_IntelliJ.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY      #Travis repo setting 설정값.
    secret_access_key: $AWS_SECRET_KEY  #Travis repo setting 설정값.
    bucket: yang-springboot-build       #s3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private                        # zip 파일 접근을 private로 한다.
    local_dir: deploy                   # before_deploy 에서 생성한 디렉토리
    wait-until-deploy: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: yang-springboot-build
    key: SpringBoot_IntelliJ.zip                # 빌드 파일을 압축해서 전달
    bundle_type: zip                            # 압축 확장자
    application: SpringBoot_IntelliJ            # CodeDeploy 애플리케이션 이름
    deployment_group: SpringBoot_IntelliJ-group # CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deploy: true

#CI 실행 완료 시 메일로 알람

notifications:
  email:
    recipients:
      -byungjoo104@gmail.com

